{% set name = "varlociraptor" %}
{% set version = "8.4.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: d62e54d9cd9365ea1ee2ae7a68ae36c1ecfd69ae6ce35d21cd0c550d11d84c52

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("varlociraptor", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - pkg-config
    - make
    - cmake
  host:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: "https://github.com/varlociraptor/varlociraptor"
  license: "GPL-3.0-or-later"
  license_family: GPL3
  summary: "Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control."
  dev_url: "https://github.com/varlociraptor/varlociraptor"
  doc_url: "https://varlociraptor.github.io"

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - biotools:varlociraptor
    - doi:10.1186/s13059-020-01993-6
